### ISSUE TITLE
includes should ignore config-appname.h

### ISSUE THREAD

**Issue by kurthindenburg** [Krazy-collection/krazy#11]
For KDE, a lot of applications have config-appname.h (ie config-konsole.h).  Krazy tags these as an issue when they are included in other files.

src/Part.h: put config.h in angle brackets line# 32 (1) 
#include "config-konsole.h"

http://ebn.kde.org/krazy/reports/kde-4.x/applications/konsole/index.html

**Comment by winterz** [comment]
it's just saying to use <config-konsole.h> instead of "config-konsole.h"

**Comment by kurthindenburg** [comment]
The config-app.h are not installed so they should use "" AFAIK

**Comment by winterz** [comment]
fixed in commit e3c72457d7a9d4f37e97b8ebd2c4d480e4c7fad0
give the EBN a couple days to catch-up
