### ISSUE TITLE
Update Copyright check to recognize SPDX headers

### ISSUE THREAD

**Issue by reporter123** [Krazy-collection/krazy#13]
KDE's licensing policy was recently updated to allow SPDX headers in lue of complete license text: https://community.kde.org/Policies/Licensing_Policy

Krazy however does not recognize such headers as valid copyright/license declarations.

http://ebn.kde.org/krazy/reports/extragear/utils/kdiff3/index.html

**Comment by winterz** [comment]
should be done now.
Should also handle SPDX copyright policy
