### ISSUE TITLE
Missing dpointer in class containing Q_DECLARE_PRIVATE_D

### ISSUE THREAD

**Issue by wojnilowicz** [Krazy-collection/krazy#6]
Issue concerns KMyMoney master branch
https://cgit.kde.org/kmymoney.git/

krazy2 reports missing dpointer if class contains
Q_DECLARE_PRIVATE_D(MyMoneyObject::d_ptr, MyMoneyAccount)

krazy2 doesn't report missing dpointer if class contains
Q_DECLARE_PRIVATE(MyMoneyAccount)

In both cases class MyMoneyAccount contains dpointer, so krazy2 report is wrong here
http://ebn.kde.org/krazy/reports/extragear/office/kmymoney/index.html
and 
// krazy:excludeall=dpointer
is needed. Please fix it.

**Comment by winterz** [comment]
fixed in ee46cdc7f4ddc66a4437aa645dd986bd93a2a5dc
