### ISSUE TITLE
krazy2 complains because of __GNUC__ define

### ISSUE THREAD

**Issue by wojnilowicz** [Krazy-collection/krazy#8]
On KMyMoney [analysis page](http://ebn.kde.org/krazy/reports/extragear/office/kmymoney/index.html) under **Check for cpp macros and usage [cpp]** a **OOPS** concerning __GNUC__ define has been reported.
We think it's not a valid check, so please change behaviour of krazy2 so that it doesn't report mentioned define as against the rules.
Please read [this post](https://phabricator.kde.org/D10164#197903) for a justification.

**Comment by winterz** [comment]
fixed in 04b5b2dde8807383eee5522cc553283e4c8379ac
